# kustomize-k8s-demo/overlays/dev/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base # Reference to the base configuration

namespace: dev-env # All resources will be deployed to the 'dev-env' namespace
namePrefix: dev-   # All resource names will be prefixed with 'dev-'

resources:
  - dev-ingress.yaml # Add the Ingress specific to dev

patches:
  - path: dev-replicas-patch.yaml # Apply the strategic merge patch
    target:
      kind: Deployment
      name: nginx-app # Target the base deployment
