# kustomize-k8s-demo/base/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest # This will be patched
        ports:
        - containerPort: 80
        resources: # Basic requests, will be patched for prod
          requests:
            memory: "64Mi"
            cpu: "100m"
